@baseUrl = http://localhost:8080

@apiKey = {{createAccount.response.body.api_key}}
@accountId = {{createAccount.response.body.id}}

### Create Account
# @name createAccount
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe.03@example.com"
}

### Get Account
GET {{baseUrl}}/accounts
X-API-Key: {{apiKey}}


@invoiceId = {{createInvoice.response.body.id}}

### Create Invoice
# @name createInvoice
POST {{baseUrl}}/invoices
X-API-Key: {{apiKey}}
Content-Type: application/json

{
    "amount": 100,
    "description": "Invoice for John Doe",
    "payment_method": "credit_card",
    "credit_card": "1234567890123456",
    "cvv": "123",
    "expiry_month": 12,
    "expiry_year": 2024,
    "holder_name": "John Doe"
}

### Get Invoice
GET {{baseUrl}}/invoices/{{invoiceId}}
X-API-Key: {{apiKey}}

### Get Invoices
GET {{baseUrl}}/invoices/account/{{accountId}}
X-API-Key: {{apiKey}}
